const commonImage = "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80";

export const productCatalog = [
  {
    name: "ABC Fire Extinguisher 6 KG",
    slug: "abc-fire-extinguisher-6kg",
    sku: "AGN-FE-ABC-6KG",
    category: "Fire Extinguishers",
    price: 2499,
    mrp: 3199,
    gstRate: 18,
    stock: 84,
    minBulkQty: 10,
    bulkPrice: 2199,
    isFeatured: true,
    rating: 4.7,
    reviews: 128,
    usageArea: "Offices, shops, apartments, schools, warehouses",
    serviceSupport: "Refill and pressure check supported",
    shortDesc: "ISI-marked multipurpose ABC extinguisher for Class A, B, and C fires.",
    description: "Stored-pressure dry powder extinguisher suited for common Indian commercial, residential, and industrial fire risks.",
    images: [commonImage],
    certifications: ["ISI", "BIS", "ISO 9001"],
    specifications: { Capacity: "6 KG", Type: "ABC Dry Powder", DischargeTime: "13-18 sec", Range: "4-6 m", Warranty: "1 year" },
    technicalData: { GST: "18%", ServiceCycle: "Yearly refill/inspection", Cylinder: "Mild steel", QRTracking: "Supported" }
  },
  {
    name: "CO2 Fire Extinguisher 4.5 KG",
    slug: "co2-fire-extinguisher-45kg",
    sku: "AGN-FE-CO2-45",
    category: "Fire Extinguishers",
    price: 6399,
    mrp: 7199,
    gstRate: 18,
    stock: 42,
    minBulkQty: 5,
    bulkPrice: 5999,
    isFeatured: true,
    rating: 4.6,
    reviews: 86,
    usageArea: "Electrical panels, UPS rooms, server rooms, labs",
    serviceSupport: "Hydro test and refilling supported",
    shortDesc: "Clean CO2 extinguisher for electrical and sensitive equipment areas.",
    description: "Non-residue extinguisher for energized electrical risks where powder or water discharge is not preferred.",
    images: [commonImage],
    certifications: ["ISI", "BIS"],
    specifications: { Capacity: "4.5 KG", Type: "CO2", DischargeTime: "10-15 sec", Range: "2-3 m", Warranty: "1 year" },
    technicalData: { GST: "18%", Cylinder: "Seamless steel", Valve: "Brass", Application: "Electrical fires" }
  },
  {
    name: "Photoelectric Smoke Detector",
    slug: "photoelectric-smoke-detector",
    sku: "AGN-SD-PE-01",
    category: "Smoke Detectors",
    price: 1199,
    mrp: 1499,
    gstRate: 18,
    stock: 120,
    minBulkQty: 20,
    bulkPrice: 999,
    isFeatured: true,
    rating: 4.5,
    reviews: 74,
    usageArea: "Homes, offices, hotels, hospitals, retail stores",
    serviceSupport: "Battery replacement reminders supported",
    shortDesc: "Fast-response smoke detector with test switch and low battery alert.",
    description: "Compact photoelectric detector for early smoke detection in low to medium risk areas.",
    images: ["https://images.unsplash.com/photo-1621905252472-943afaa20e20?auto=format&fit=crop&w=1200&q=80"],
    certifications: ["CE", "RoHS"],
    specifications: { Sensor: "Photoelectric", Alarm: "85 dB", Battery: "9V", Coverage: "20-25 sqm" },
    technicalData: { GST: "18%", OperatingTemp: "-10C to 50C", Humidity: "95% RH", QRTracking: "Optional" }
  },
  {
    name: "Addressable Fire Alarm Control Panel",
    slug: "addressable-fire-alarm-control-panel",
    sku: "AGN-FA-PANEL-02",
    category: "Fire Alarms",
    price: 28500,
    mrp: 32900,
    gstRate: 18,
    stock: 18,
    minBulkQty: 2,
    bulkPrice: 26900,
    isFeatured: true,
    rating: 4.8,
    reviews: 32,
    usageArea: "Commercial buildings, schools, hospitals, factories",
    serviceSupport: "Installation and commissioning available",
    shortDesc: "Two-loop addressable fire alarm panel for structured detection systems.",
    description: "A reliable alarm control panel for sites that need zone visibility, event logs, and maintainable detection infrastructure.",
    images: [commonImage],
    certifications: ["CE", "ISO 9001"],
    specifications: { Loops: "2", Zones: "Up to 64 devices", Power: "230V AC", BatteryBackup: "24V DC" },
    technicalData: { GST: "18%", Installation: "Technician required", AMC: "Recommended", Warranty: "1 year" }
  },
  {
    name: "Fire Hose Reel Drum 30 Meter",
    slug: "fire-hose-reel-drum-30m",
    sku: "AGN-HOSE-REEL-30",
    category: "Fire Hose Reels",
    price: 11800,
    mrp: 13400,
    gstRate: 18,
    stock: 26,
    minBulkQty: 3,
    bulkPrice: 10900,
    isFeatured: false,
    rating: 4.4,
    reviews: 41,
    usageArea: "Basements, factories, malls, parking areas",
    serviceSupport: "Hydrant inspection and pressure testing supported",
    shortDesc: "Wall-mounted hose reel drum with 30 meter reinforced hose.",
    description: "Durable hose reel for first response water-based firefighting in hydrant-equipped buildings.",
    images: [commonImage],
    certifications: ["ISI", "BIS"],
    specifications: { Length: "30 m", HoseDiameter: "19 mm", Mounting: "Wall mounted", Nozzle: "Jet/spray" },
    technicalData: { GST: "18%", PressureTest: "Required annually", Material: "MS drum", Finish: "Powder coated" }
  },
  {
    name: "Landing Valve Hydrant Set",
    slug: "landing-valve-hydrant-set",
    sku: "AGN-HYD-LV-01",
    category: "Hydrant Systems",
    price: 7400,
    mrp: 8500,
    gstRate: 18,
    stock: 30,
    minBulkQty: 5,
    bulkPrice: 6999,
    isFeatured: false,
    rating: 4.5,
    reviews: 28,
    usageArea: "Industrial hydrant lines and commercial fire risers",
    serviceSupport: "Installation inspection supported",
    shortDesc: "Single headed landing valve for hydrant system installations.",
    description: "Heavy duty landing valve for hydrant systems in factories, warehouses, commercial towers, and institutions.",
    images: [commonImage],
    certifications: ["ISI", "BIS"],
    specifications: { Size: "63 mm", Type: "Single headed", Material: "Gunmetal", Inlet: "Flanged" },
    technicalData: { GST: "18%", Testing: "Hydro pressure test", AMC: "Supported", Warranty: "1 year" }
  },
  {
    name: "Pendant Fire Sprinkler 68C",
    slug: "pendant-fire-sprinkler-68c",
    sku: "AGN-SPR-P68",
    category: "Sprinklers",
    price: 349,
    mrp: 425,
    gstRate: 18,
    stock: 500,
    minBulkQty: 50,
    bulkPrice: 315,
    isFeatured: false,
    rating: 4.3,
    reviews: 59,
    usageArea: "Offices, hotels, warehouses, parking basements",
    serviceSupport: "System design and inspection available",
    shortDesc: "Standard response pendant sprinkler with 68C rating.",
    description: "Sprinkler head for automatic water-based suppression systems in compliant building installations.",
    images: [commonImage],
    certifications: ["UL Listed", "FM Approved"],
    specifications: { Temperature: "68C", Thread: "1/2 inch NPT", Finish: "Chrome", KFactor: "5.6" },
    technicalData: { GST: "18%", Installation: "Licensed installer recommended", Inspection: "Quarterly visual check" }
  },
  {
    name: "Fiberglass Fire Blanket 1.8 x 1.8 m",
    slug: "fiberglass-fire-blanket-18m",
    sku: "AGN-FB-BLANKET-18",
    category: "Fire Blankets",
    price: 899,
    mrp: 1199,
    gstRate: 18,
    stock: 140,
    minBulkQty: 15,
    bulkPrice: 799,
    isFeatured: false,
    rating: 4.6,
    reviews: 101,
    usageArea: "Kitchens, labs, workshops, small offices",
    serviceSupport: "Replacement reminder supported",
    shortDesc: "Quick-access fiberglass blanket for small flame containment.",
    description: "A compact wall-mounted blanket for kitchen and small workplace fire response.",
    images: [commonImage],
    certifications: ["CE"],
    specifications: { Size: "1.8 x 1.8 m", Material: "Fiberglass", Case: "Wall pouch", Use: "Single emergency use" },
    technicalData: { GST: "18%", Service: "Replacement after use", QRTracking: "Optional" }
  },
  {
    name: "ISI Safety Helmet",
    slug: "isi-safety-helmet",
    sku: "AGN-PPE-HELMET-ISI",
    category: "Safety Helmets",
    price: 299,
    mrp: 399,
    gstRate: 18,
    stock: 650,
    minBulkQty: 50,
    bulkPrice: 249,
    isFeatured: false,
    rating: 4.4,
    reviews: 210,
    usageArea: "Construction, factories, warehouses, maintenance teams",
    serviceSupport: "Bulk contractor supply supported",
    shortDesc: "ISI-marked industrial helmet with adjustable ratchet support.",
    description: "Lightweight helmet for industrial and construction safety compliance.",
    images: [commonImage],
    certifications: ["ISI"],
    specifications: { Material: "HDPE", Suspension: "Ratchet", Colors: "White/Yellow/Blue/Red", Standard: "IS 2925" },
    technicalData: { GST: "18%", BulkBranding: "Available", Warranty: "6 months" }
  },
  {
    name: "Industrial PPE Kit",
    slug: "industrial-ppe-kit",
    sku: "AGN-PPE-KIT-01",
    category: "PPE Kits",
    price: 1799,
    mrp: 2299,
    gstRate: 18,
    stock: 95,
    minBulkQty: 20,
    bulkPrice: 1599,
    isFeatured: true,
    rating: 4.5,
    reviews: 88,
    usageArea: "Maintenance, inspection, shutdown work, visitor safety",
    serviceSupport: "Bulk supply and replenishment supported",
    shortDesc: "Helmet, gloves, goggles, mask, reflective jacket, and storage bag.",
    description: "Ready-to-use industrial PPE kit for safety teams, contractors, and site visitors.",
    images: [commonImage],
    certifications: ["ISO 9001"],
    specifications: { Includes: "6 items", Jacket: "Reflective", Gloves: "Nitrile-coated", Bag: "Reusable" },
    technicalData: { GST: "18%", Customization: "Logo printing available", Reorder: "Supported" }
  },
  {
    name: "LED Emergency Exit Light",
    slug: "led-emergency-exit-light",
    sku: "AGN-EXIT-LED-01",
    category: "Exit Lights",
    price: 1299,
    mrp: 1699,
    gstRate: 18,
    stock: 180,
    minBulkQty: 20,
    bulkPrice: 1149,
    isFeatured: false,
    rating: 4.4,
    reviews: 67,
    usageArea: "Staircases, corridors, malls, hotels, offices",
    serviceSupport: "Battery health reminder supported",
    shortDesc: "Wall-mounted LED exit sign with battery backup.",
    description: "Emergency direction signage for evacuation routes and compliance readiness.",
    images: [commonImage],
    certifications: ["CE", "RoHS"],
    specifications: { Backup: "2-3 hours", Input: "230V AC", Mounting: "Wall/ceiling", Legend: "Exit" },
    technicalData: { GST: "18%", BatteryReplacement: "Supported", Inspection: "Monthly test recommended" }
  },
  {
    name: "LPG Gas Leak Detector",
    slug: "lpg-gas-leak-detector",
    sku: "AGN-GAS-LPG-01",
    category: "Gas Leak Detectors",
    price: 2199,
    mrp: 2799,
    gstRate: 18,
    stock: 70,
    minBulkQty: 10,
    bulkPrice: 1999,
    isFeatured: false,
    rating: 4.6,
    reviews: 53,
    usageArea: "Commercial kitchens, restaurants, canteens, LPG storage",
    serviceSupport: "Calibration reminder supported",
    shortDesc: "LPG detector with audible alarm and relay output support.",
    description: "Early warning detector for LPG leakage in kitchens and utility areas.",
    images: [commonImage],
    certifications: ["CE"],
    specifications: { Gas: "LPG", Alarm: "85 dB", Input: "230V AC", Relay: "Optional" },
    technicalData: { GST: "18%", Calibration: "Annual", Installation: "Wall mounted" }
  },
  {
    name: "Workplace First Aid Kit Large",
    slug: "workplace-first-aid-kit-large",
    sku: "AGN-FAK-LARGE",
    category: "First Aid Kits",
    price: 1499,
    mrp: 1899,
    gstRate: 12,
    stock: 110,
    minBulkQty: 10,
    bulkPrice: 1299,
    isFeatured: false,
    rating: 4.5,
    reviews: 143,
    usageArea: "Offices, factories, schools, warehouses, vehicles",
    serviceSupport: "Replenishment reminder supported",
    shortDesc: "Wall-mountable first aid kit for workplace emergency readiness.",
    description: "Large workplace first aid box with bandages, dressing, antiseptic, gloves, and basic emergency supplies.",
    images: [commonImage],
    certifications: ["ISO 13485 supplier"],
    specifications: { Size: "Large", Mounting: "Wall", Items: "40+ pieces", Case: "ABS box" },
    technicalData: { GST: "12%", Refill: "Available", Inspection: "Monthly stock check" }
  },
  {
    name: "Fire Resistant Document Safe",
    slug: "fire-resistant-document-safe",
    sku: "AGN-STORAGE-FR-SAFE",
    category: "Fire Resistant Storage",
    price: 18999,
    mrp: 22999,
    gstRate: 18,
    stock: 12,
    minBulkQty: 2,
    bulkPrice: 17999,
    isFeatured: false,
    rating: 4.3,
    reviews: 19,
    usageArea: "Offices, finance rooms, records rooms, shops",
    serviceSupport: "Delivery and installation support available",
    shortDesc: "Fire-resistant safe for documents, contracts, and business records.",
    description: "Secure storage solution for critical records in commercial and office environments.",
    images: [commonImage],
    certifications: ["Fire-resistant rated"],
    specifications: { Capacity: "55 L", Lock: "Digital", Shelves: "1", Finish: "Powder coated" },
    technicalData: { GST: "18%", Delivery: "Chargeable", Warranty: "1 year" }
  },
  {
    name: "Electrical Safety Lockout Kit",
    slug: "electrical-safety-lockout-kit",
    sku: "AGN-ELEC-LOTO-01",
    category: "Electrical Safety Equipment",
    price: 3899,
    mrp: 4599,
    gstRate: 18,
    stock: 55,
    minBulkQty: 10,
    bulkPrice: 3499,
    isFeatured: false,
    rating: 4.4,
    reviews: 38,
    usageArea: "Factories, maintenance rooms, electrical panels",
    serviceSupport: "Contractor bulk supply supported",
    shortDesc: "Lockout tagout kit for electrical maintenance safety.",
    description: "Practical electrical safety kit for maintenance isolation and workplace safety compliance.",
    images: [commonImage],
    certifications: ["OSHA-style LOTO compatible"],
    specifications: { Padlocks: "4", Tags: "10", Hasps: "2", Case: "Portable pouch" },
    technicalData: { GST: "18%", Training: "Available on request", Bulk: "Supported" }
  }
];
